algo: "pareto_critic"
state_dim: 27
action_dim: 1
reward_dim: 8
response_dim: 8
max_action: 150
max_buffer_size: 5000000
discount: 0.99
tau: 0.001

max_steps: 240000
test_every: 10
log_every: 10
print_every: 1000
save_every: 10000

batch_size: 512

save_model: False
use_tensorboard: True
bc_loss_coeff: 0.01

reward_service: 1
reward_business: 1
reward_cleanliness: 1
reward_check_in: 1
reward_value: 1
reward_rooms: 1
reward_location: 1
reward_overall: 100